# Generated by Django 5.1.2 on 2024-11-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_order_emails',
            field=models.BooleanField(default=True, verbose_name='Recibir correos de pedidos sin asignación'),
        ),
    ]
