# Generated by Django 5.1.2 on 2024-11-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_customuser_receive_order_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_assignment_emails',
            field=models.BooleanField(default=True, verbose_name='Recibir correos de aviso de asignación de pedidos'),
        ),
    ]
