# Generated by Django 5.1.3 on 2024-11-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('task', models.CharField(choices=[('repair_equipment', 'Reparación de equipo'), ('install_equipment', 'Instalación de equipo'), ('repair_building', 'Reparación edilicia'), ('device_manufacture', 'Fabricación de dispositivo'), ('informatics_order', 'Pedido a informática')], max_length=20)),
                ('equipment_type', models.CharField(blank=True, max_length=100)),
                ('physical_location', models.CharField(max_length=100)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('low', 'Baja'), ('high', 'Alta')], default='normal', max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('conicet_id', models.CharField(blank=True, max_length=50)),
                ('bill_to', models.CharField(choices=[('subsidy', 'Subsidio'), ('ibr', 'IBR')], max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('failure_description', models.TextField()),
                ('sworn_statement', models.BooleanField(default=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('technical_report', models.TextField(blank=True)),
                ('completion_percentage', models.IntegerField(choices=[(0, '0%'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignada'), ('completed', 'Finalizada')], default='pending', max_length=10)),
            ],
        ),
    ]
