# Generated by Django 5.1.2 on 2024-11-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
